# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/amazon/crown/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/amazon/crown

PRODUCT_COPY_FILES += \
    vendor/amazon/crown/proprietary/vendor/lib/libcameracustom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcameracustom.so \
    vendor/amazon/crown/proprietary/etc/audio_device.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/audio_device.xml \
    vendor/amazon/crown/proprietary/lib/libasp.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libasp.so \
    vendor/amazon/crown/proprietary/lib/libaspclient.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libaspclient.so \
    vendor/amazon/crown/proprietary/lib/liblatencybenchmarker.so:$(TARGET_COPY_OUT_SYSTEM)/lib/liblatencybenchmarker.so \
    vendor/amazon/crown/proprietary/lib/libmediaextension.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmediaextension.so \
    vendor/amazon/crown/proprietary/lib/libsmartvolume.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsmartvolume.so \
    vendor/amazon/crown/proprietary/vendor/firmware/EEPROM_MT7668.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/EEPROM_MT7668.bin \
    vendor/amazon/crown/proprietary/vendor/firmware/TxPwrLimit_MT76x8.dat:$(TARGET_COPY_OUT_VENDOR)/firmware/TxPwrLimit_MT76x8.dat \
    vendor/amazon/crown/proprietary/vendor/firmware/WIFI_RAM_CODE2_SDIO_MT7668.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/WIFI_RAM_CODE2_SDIO_MT7668.bin \
    vendor/amazon/crown/proprietary/vendor/firmware/WIFI_RAM_CODE_MT7668.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/WIFI_RAM_CODE_MT7668.bin \
    vendor/amazon/crown/proprietary/vendor/firmware/mt7668_patch_e2_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt7668_patch_e2_hdr.bin \
    vendor/amazon/crown/proprietary/vendor/firmware/wifi.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi.cfg \
    vendor/amazon/crown/proprietary/vendor/bin/nvram_daemon:$(TARGET_COPY_OUT_VENDOR)/bin/nvram_daemon \
    vendor/amazon/crown/proprietary/vendor/etc/audio-algorithms/AFE.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/audio-algorithms/AFE.cfg \
    vendor/amazon/crown/proprietary/vendor/etc/audio-algorithms/EQ_100.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/audio-algorithms/EQ_100.cfg \
    vendor/amazon/crown/proprietary/vendor/etc/audio-algorithms/EQ_30.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/audio-algorithms/EQ_30.cfg \
    vendor/amazon/crown/proprietary/vendor/etc/audio-algorithms/EQ_50.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/audio-algorithms/EQ_50.cfg \
    vendor/amazon/crown/proprietary/vendor/etc/audio-algorithms/EQ_70.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/audio-algorithms/EQ_70.cfg \
    vendor/amazon/crown/proprietary/vendor/etc/audio-algorithms/EdgeflowModelConfig.json:$(TARGET_COPY_OUT_VENDOR)/etc/audio-algorithms/EdgeflowModelConfig.json \
    vendor/amazon/crown/proprietary/vendor/etc/audio-algorithms/MBCL_10percent.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/audio-algorithms/MBCL_10percent.cfg \
    vendor/amazon/crown/proprietary/vendor/etc/audio-algorithms/MBCL_20percent.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/audio-algorithms/MBCL_20percent.cfg \
    vendor/amazon/crown/proprietary/vendor/etc/audio-algorithms/MBCL_VOIP.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/audio-algorithms/MBCL_VOIP.cfg \
    vendor/amazon/crown/proprietary/vendor/etc/audio-algorithms/MBCL_VOIP_10percent.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/audio-algorithms/MBCL_VOIP_10percent.cfg \
    vendor/amazon/crown/proprietary/vendor/etc/audio-algorithms/MBCL_VOIP_20percent.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/audio-algorithms/MBCL_VOIP_20percent.cfg \
    vendor/amazon/crown/proprietary/vendor/etc/audio-algorithms/MBCL_default.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/audio-algorithms/MBCL_default.cfg \
    vendor/amazon/crown/proprietary/vendor/etc/audio-algorithms/SpatialAudio_MonoEQ.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/audio-algorithms/SpatialAudio_MonoEQ.cfg \
    vendor/amazon/crown/proprietary/vendor/etc/audio-algorithms/SpatialAudio_SideContentEQ.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/audio-algorithms/SpatialAudio_SideContentEQ.cfg \
    vendor/amazon/crown/proprietary/vendor/etc/audio-algorithms/SpatialAudio_UnityEQ.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/audio-algorithms/SpatialAudio_UnityEQ.cfg \
    vendor/amazon/crown/proprietary/vendor/etc/audio-algorithms/SpatialAudio_XTC_Cont_FIR_d_546.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/audio-algorithms/SpatialAudio_XTC_Cont_FIR_d_546.cfg \
    vendor/amazon/crown/proprietary/vendor/etc/audio-algorithms/SpatialAudio_XTC_Ipsi_FIR_d_546.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/audio-algorithms/SpatialAudio_XTC_Ipsi_FIR_d_546.cfg \
    vendor/amazon/crown/proprietary/vendor/etc/audio-algorithms/SpatialAudio_ZeroEQ.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/audio-algorithms/SpatialAudio_ZeroEQ.cfg \
    vendor/amazon/crown/proprietary/vendor/etc/audio-algorithms/UserEQ.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/audio-algorithms/UserEQ.cfg \
    vendor/amazon/crown/proprietary/vendor/etc/audio-algorithms/VOIPRxParametricEQ.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/audio-algorithms/VOIPRxParametricEQ.cfg \
    vendor/amazon/crown/proprietary/vendor/etc/audio-algorithms/VOIPTxParametricEQ.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/audio-algorithms/VOIPTxParametricEQ.cfg \
    vendor/amazon/crown/proprietary/vendor/etc/audio-algorithms/asp.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/audio-algorithms/asp.cfg \
    vendor/amazon/crown/proprietary/vendor/etc/audio-algorithms/coefs_FBF.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/audio-algorithms/coefs_FBF.cfg \
    vendor/amazon/crown/proprietary/vendor/etc/audio-algorithms/coefs_FBFV2_LowLatency_8beams.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/audio-algorithms/coefs_FBFV2_LowLatency_8beams.cfg \
    vendor/amazon/crown/proprietary/vendor/etc/audio-algorithms/coefs_FilterBank_160.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/audio-algorithms/coefs_FilterBank_160.cfg \
    vendor/amazon/crown/proprietary/vendor/etc/audio-algorithms/coefs_FilterBank_640.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/audio-algorithms/coefs_FilterBank_640.cfg \
    vendor/amazon/crown/proprietary/vendor/etc/audio-algorithms/coefs_FilterBank_AnaSyn_M512_D128_Lh512.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/audio-algorithms/coefs_FilterBank_AnaSyn_M512_D128_Lh512.cfg \
    vendor/amazon/crown/proprietary/vendor/etc/audio-algorithms/coefs_FilterBank_AnalysisSynthesis_768cvxGLow.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/audio-algorithms/coefs_FilterBank_AnalysisSynthesis_768cvxGLow.cfg \
    vendor/amazon/crown/proprietary/vendor/etc/audio-algorithms/dtd_cpd_priors.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/audio-algorithms/dtd_cpd_priors.cfg \
    vendor/amazon/crown/proprietary/vendor/etc/audio-algorithms/es_cpd_priors.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/audio-algorithms/es_cpd_priors.cfg \
    vendor/amazon/crown/proprietary/vendor/etc/audio-algorithms/hamming512_earcon.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/audio-algorithms/hamming512_earcon.cfg \
    vendor/amazon/crown/proprietary/vendor/etc/audio-algorithms/ue_cpd_priors.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/audio-algorithms/ue_cpd_priors.cfg \
    vendor/amazon/crown/proprietary/vendor/etc/audio-algorithms/vad_cpd_priors.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/audio-algorithms/vad_cpd_priors.cfg \
    vendor/amazon/crown/proprietary/vendor/etc/audio-algorithms/vad_lite.tflite:$(TARGET_COPY_OUT_VENDOR)/etc/audio-algorithms/vad_lite.tflite \
    vendor/amazon/crown/proprietary/vendor/etc/audio-algorithms/vss_cpd_priors.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/audio-algorithms/vss_cpd_priors.cfg \
    vendor/amazon/crown/proprietary/vendor/etc/audio_device.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_device.xml \
    vendor/amazon/crown/proprietary/vendor/etc/audio_em.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_em.xml \
    vendor/amazon/crown/proprietary/vendor/etc/audio_param/AudioParamOptions.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/AudioParamOptions.xml \
    vendor/amazon/crown/proprietary/vendor/lib/hw/audio.primary_amazon.mt8163.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/audio.primary_amazon.mt8163.so \
    vendor/amazon/crown/proprietary/vendor/lib/hw/audio.usb.mt8163.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/audio.usb.mt8163.so \
    vendor/amazon/crown/proprietary/vendor/lib/libaudiocompensationfilter.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudiocompensationfilter.so \
    vendor/amazon/crown/proprietary/vendor/lib/libaudiocomponentengine.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudiocomponentengine.so \
    vendor/amazon/crown/proprietary/vendor/lib/libaudiocustparam.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudiocustparam.so \
    vendor/amazon/crown/proprietary/vendor/lib/libaudiodcrflt.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudiodcrflt.so \
    vendor/amazon/crown/proprietary/vendor/lib/libaudiosetting.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudiosetting.so \
    vendor/amazon/crown/proprietary/vendor/lib/libaudiotoolkit.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudiotoolkit.so \
    vendor/amazon/crown/proprietary/vendor/lib/libbessound_hd_mtk.so:$(TARGET_COPY_OUT_VENDOR)/lib/libbessound_hd_mtk.so \
    vendor/amazon/crown/proprietary/vendor/lib/libblisrc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libblisrc.so \
    vendor/amazon/crown/proprietary/vendor/lib/libblisrc32.so:$(TARGET_COPY_OUT_VENDOR)/lib/libblisrc32.so \
    vendor/amazon/crown/proprietary/vendor/lib/libcustom_nvram.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcustom_nvram.so \
    vendor/amazon/crown/proprietary/vendor/lib/libcvsd_mtk.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcvsd_mtk.so \
    vendor/amazon/crown/proprietary/vendor/lib/libfile_op.so:$(TARGET_COPY_OUT_VENDOR)/lib/libfile_op.so \
    vendor/amazon/crown/proprietary/vendor/lib/libmsbc_mtk.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmsbc_mtk.so \
    vendor/amazon/crown/proprietary/vendor/lib/libmtklimiter.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmtklimiter.so \
    vendor/amazon/crown/proprietary/vendor/lib/libmtkplayer.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmtkplayer.so \
    vendor/amazon/crown/proprietary/vendor/lib/libmtkshifter.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmtkshifter.so \
    vendor/amazon/crown/proprietary/vendor/lib/libnvram.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvram.so \
    vendor/amazon/crown/proprietary/vendor/lib/libnvram_daemon_callback.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvram_daemon_callback.so \
    vendor/amazon/crown/proprietary/vendor/lib/libnvram_platform.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvram_platform.so \
    vendor/amazon/crown/proprietary/vendor/lib/libnvramagentclient.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvramagentclient.so \
    vendor/amazon/crown/proprietary/vendor/lib/libspeech_enh_lib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libspeech_enh_lib.so
